env:
  browser: true
  commonjs: true
  es6: true
  node: true
  react-native/react-native: true
extends:
  - eslint:recommended
  - plugin:react/recommended
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - react-native
settings:
  react:
    version: 16.3.1
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - off
    - single
  semi:
    - error
    - never
  no-console: off
  react/jsx-uses-react:
    - error
  react/jsx-uses-vars:
    - error
  react/prop-types: 0
